name:               miso-vue-example
version:            0.1.0.0
synopsis:           GHCJS + Miso port of the Vue.js examples.
category:           Web
author:             TAKAHASHI Yuto <ytaka23dev@gmail.com>
maintainer:         TAKAHASHI Yuto <ytaka23dev@gmail.com>
copyright:          Copyright (C) 2018 TAKAHASHI Yuto
license:            BSD3
github:             y-taka-23/miso-vue-example

dependencies:
- base
- miso

executables:

  github-commits:
    main:           Main.hs
    source-dirs:    github-commits
    dependencies:
    - aeson
    - ghcjs-base

  svg-graph:
    main:           Main.hs
    source-dirs:    svg-graph
    dependencies:
    - aeson
    - aeson-pretty
    - containers
